from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from sqlalchemy.orm import Session

from app.config import settings
from app.models.land_record import FIELD_NAMES, LandRecord
from app.models.user import User
from app.models.report import Report
from app.services.audit_service import log_action

NAVY = colors.HexColor("#1e3a5f")
TAN = colors.HexColor("#d4a574")
MUTED = colors.HexColor("#6b6560")
BORDER = colors.HexColor("#d1ccc6")

FIELD_LABELS = {
    "owner_name": "Owner Name", "father_name": "Father's / Guardian's Name",
    "survey_number": "Survey Number", "khasra_number": "Khasra Number",
    "khata_number": "Khata Number", "plot_area": "Plot Area", "village": "Village",
    "tehsil": "Tehsil", "district": "District", "land_classification": "Land Classification",
    "mutation_number": "Mutation Number", "registration_number": "Registration Number",
}


def generate_record_pdf(db: Session, record: LandRecord, actor: User) -> Report:
    reports_dir = Path(settings.STORAGE_PATH) / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    out_path = reports_dir / f"{record.record_code}.pdf"

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("BPTitle", parent=styles["Title"], textColor=NAVY, fontSize=20, spaceAfter=2)
    sub_style = ParagraphStyle("BPSub", parent=styles["Normal"], textColor=MUTED, fontSize=9)
    section_style = ParagraphStyle("BPSection", parent=styles["Heading2"], textColor=NAVY, fontSize=12, spaceBefore=14, spaceAfter=6)
    note_style = ParagraphStyle("BPNote", parent=styles["Normal"], textColor=MUTED, fontSize=8, spaceBefore=10)

    doc = SimpleDocTemplate(str(out_path), pagesize=A4,
                             topMargin=20 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm)
    story = []
    story.append(Paragraph("BHUMI PRAMAN", title_style))
    story.append(Paragraph("Intelligent Land Record Digitization &amp; Validation &middot; SIH 2026, PS 26018 (Prototype)", sub_style))
    story.append(Spacer(1, 10))

    status_label = {"verified": "OFFICIALLY VERIFIED", "pending_review": "PENDING VERIFICATION", "rejected": "REJECTED"}.get(record.status, record.status.upper())
    status_color = {"verified": colors.HexColor("#15803d"), "pending_review": colors.HexColor("#d97706"), "rejected": colors.HexColor("#b91c1c")}.get(record.status, NAVY)
    story.append(Paragraph(f'<font color="{status_color.hexval()}"><b>{status_label}</b></font> &nbsp;&nbsp; Record ID: <b>{record.record_code}</b>', styles["Normal"]))

    story.append(Paragraph("Land Record Details", section_style))
    rows = [["Field", "Value"]]
    for name in FIELD_NAMES:
        value = getattr(record, name) or "—"
        rows.append([FIELD_LABELS[name], value])
    table = Table(rows, colWidths=[55 * mm, 110 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f6f3")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)

    story.append(Paragraph("Validation &amp; Verification", section_style))
    import json
    issues = json.loads(record.validation_issues_json or "[]")
    dupes = json.loads(record.duplicate_of_json or "[]")
    conflicts = json.loads(record.conflicts_json or "[]")
    meta_rows = [
        ["Validation issues", str(len(issues)) if issues else "None"],
        ["Potential duplicates", ", ".join(dupes) if dupes else "None"],
        ["Potential ownership conflicts", str(len(conflicts)) if conflicts else "None"],
        ["AI record confidence (at extraction)", f"{record.record_confidence * 100:.1f}%"],
        ["Verified by", record.verified_by.full_name if record.verified_by_id and record.verified_by else "—"],
        ["Verified at", record.verified_at.strftime("%d %b %Y, %H:%M UTC") if record.verified_at else "—"],
        ["Record integrity hash (SHA-256)", record.verification_hash or "—"],
        ["Report generated", datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")],
        ["Generated by", actor.full_name],
    ]
    meta_table = Table(meta_rows, colWidths=[65 * mm, 100 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)

    story.append(Paragraph(
        "This record was produced by a Smart India Hackathon 2026 (Problem Statement 26018) student "
        "prototype. Field values were extracted by an AI/OCR pipeline and are shown alongside their "
        "system-assigned confidence at extraction time; any field an officer edited or accepted is "
        "recorded in the platform's audit trail. This document does not constitute an official "
        "government land record.", note_style,
    ))

    doc.build(story)

    report = Report(land_record_id=record.id, generated_by_id=actor.id, file_path=str(out_path))
    db.add(report)
    db.commit()
    db.refresh(report)
    log_action(db, actor, "report.generated", "land_record", record.id, notes=str(out_path))
    return report
